name: "restore-savepoint"
version: "0.1.0"
description: "Upgrades (--install) a Flink job from the selected valid savepoint."
command: "$HELM_PLUGIN_DIR/flink-state-manager.sh"
hooks:
  install: "chmod +x $HELM_PLUGIN_DIR/flink-state-manager.sh"
